= scheme-motions.nvim

Motions that feel good (to me) for editing s-expressions.

Lisps are uniquely poorly suited to the character & line-wise editing model Vim provides.
Tree-sitter allows for a significantly better experience, operating on the nodes that represent the forms/expressions themselves.


== Status
Just playin' around.

I have no hope or aspirations that this will ever become more than a pet project.
Learning how to "correctly" structure a Lua nvim plugin.

Maybe playing around with https://fennel-lang.org/[Fennel] down the line.


== Musings
.To wrap, or not to wrap?
Not yet sure if I want to re-wrap the `TSNode` and `TSTree` objects to add more comparisons and methods.
May help to give a more global `:next()` w/ respect to the tree, rather than default `:next_sibling()`.

_Update:_ <br>

So I found a way to do it, but it's pretty hacky.

[source,lua]
----
local Node = {}
function Node:new(TSNode)
   return setmetatable({}, {
      __index = function(_, key)
         return function(...)
            return TSNode[key](TSNode, ...)
         end
      end
   })
end
----

Dooonn't think that's on the radar for now.
Feels likely to make troubleshooting, debugging, much more difficult.


== Inspiration, awe, theft, etc.
. https://github.com/julienvincent/nvim-paredit
. https://github.com/kovisoft/paredit
. https://github.com/gpanders/nvim-parinfer
