= scm-edit.nvim
:toc:                      preamble
:toclevels:                3
:source-highlighter:       pygments
:pygments-style:           algol_nu
:pygments-linenums-mode:   table

Motions that feel good (to me) for editing s-expressions.

Lisps are uniquely poorly suited to the character & line-wise editing model Vim provides.
Tree-sitter allows for a significantly better experience, operating on the nodes that represent the forms/expressions themselves.


== Status
Just playin' around.

I have no hope or aspirations that this will ever become more than a pet project.
Learning how to "correctly" structure a Lua nvim plugin.

Maybe mess around with https://fennel-lang.org/[Fennel].


== Musings
=== To wrap, or not to wrap
Not yet sure if I want to re-wrap the `TSNode` and `TSTree` objects to add more comparisons and methods.
May help to give a more global `:next()` w/ respect to the tree, rather than default `:next_sibling()`.

_Update:_ +
So I found a way to do it, but it's pretty hacky.

[source,lua]
----
local Node = {}

function Node:new(node)
   -- Pretty safe to assume *one* of these will be necessary every time.
   local start_row, start_column, end_row, end_column = node:range()

   return setmetatable({
      _node        = node,
      start_row    = start_row,
      start_column = start_column,
      end_row      = end_row,
      end_column   = end_column - 1,  -- non-inclusive upper bound offset.
   }, {
      __index = function(_, key)
         return self[key] or function(...)
            return node[key](node, ...)
         end
      end
   })
end

return Node
----

Dooonn't think that's on the radar for now.
Feels likely to make troubleshooting, debugging, much more difficult.

=== Modularity
Ideally each piece should be nearly independently usable
(with exceptions for `Cursor`, or other core "classes").

=== Contextual movements
Repeated movements (or perhaps all "big" movements?) should not exceed "`contextual boundaries`".
When in a comment, `4W` should not jump outside of the comment context into code.
When in code, `{` should jump back to the prior top-level definition, not a prior comment paragraph.

.Update 2024-03-17
Thinking the above actually may be rather difficult to implement.
As I think about it furthere, there are more context-dependent scenarios than I considered.
Example:

[source,scheme]
----
(element1 "this is a string" |element2)
;;                  cursor --^
;; When pressing `b', the consistent expectation would be to place the cursor
;; within the string, at the start of the word "string". Need to consider the
;; context of the *expected destination*.
----

For now, it may be easiest to not remap the default `b`, `w`, `e`, bindings, and instead use `sb`, `sw`, and `se`.
When the core of the movement is sound, adding in contextual mappings becomes easier.
Currently there are unmitigated edge cases (prev element within form, prev element at form end, etc.) that make extensibility difficult.


== Complete
=== Motions
.Completed
. `motions.next_form_start`
. `motions.prev_form_start`
. `motions.next_element_start`
. `motions.prev_element_start`
. `motions.next_element_end`

=== Selecting
NYI.

.Wishlist
. Select in form
. Select around form
. Select in definition
. Select around definition

=== Editing
NYI.

.Wishlist
. Move element, form forwards/backwards/up
. Wrap element, form, visual selection
. Unwrap form
. Slurp/barf

=== Autopairs
.Completed
. `pairs.close_one`
. `pairs.close_all`
. `pairs.toggle`

.Wishlist
. Deleting a paren deletes its match


== Inspiration, awe, theft, etc.
. https://github.com/julienvincent/nvim-paredit
. https://github.com/kovisoft/paredit
. https://github.com/gpanders/nvim-parinfer
